# Generated by Django 6.0.2 on 2026-05-13 12:13

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='current', max_length=32, unique=True)),
                ('state', models.JSONField(default=mainapp.models.default_chess_state)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chess game state',
                'verbose_name_plural': 'Chess game states',
            },
        ),
    ]
